version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: pipra_app
    container_name: pipra_app
    restart: unless-stopped 
    working_dir: /var/www 
    volumes:
      - ./:/var/www
    networks:
            - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: pipra_db
    restart: unless-stopped 
    ports:
      - "8386:3306" 
    environment:
      MYSQL_DATABASE: pipra #database name
      MYSQL_ROOT_PASSWORD: pipra_root #database root password
      MYSQL_PASSWORD: pipra_pass #database password
      MYSQL_USER: pipra_sajid #database user
    volumes:
      - pipra_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  pipra_data:

networks:
  laravel:
    driver: bridge
